### ISSUE TITLE
Licence file missing

### ISSUE THREAD

**Issue by rolandf** [adamspd/crueltouch#85]
Hello,
this work is awesome.

Could you please clarify on what licence it is distributed ?

Personnally I'd like to reuse the client facing appointment workflow using FullCalendar and the backend to let the site owner review the appointment. Anything related to photography would not be used.

Best regards,
Frédéric

**Comment by adamspd** [comment]
Hi @rolandf,

Thank you for your kind words.

As of now, I haven't applied a specific open-source licence to the project.

But the part you're specifically interested in is however a package I wrote called [django-appointment](https://github.com/adamspd/django-appointment), which is available for use and is easy to install in your project through [PyPI](https://pypi.org/project/django-appointment/). This package itself is distributed under its own license, so you might want to check that for compliance with your intended use.

If you're interested in reusing parts of my project directly, please let me know more about your use case. I might be able to grant you a specific permission or consider applying a more permissive license to the project to facilitate this kind of reuse.

Thanks again for your interest, and if you find the django-appointment package useful, please consider giving it a star (on GitHub). It helps a lot!

Best regards,
Adams
